{% set name = "copulae" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66f0b015ff82ef9ec491a17cb314f02ddc46372eb1ab3cc75135ed0ea536008a

build:
  number: 6
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - numpy 1.14.*  # [py==37]
    - numpy 1.12.*  # [py!=37]
  run:
    - pandas >=0.24
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1
    - statsmodels >=0.9

test:
  imports:
    - copulae
    - copulae.archimedean
    - copulae.copula
    - copulae.core
    - copulae.datasets
    - copulae.elliptical
    - copulae.gof
    - copulae.indep
    - copulae.special
    - copulae.stats
    - copulae.utility

about:
  home: https://github.com/DanielBok/copulae
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python copulae library for dependency modelling
  doc_url: https://copulae.readthedocs.io/en/latest
  dev_url: https://github.com/DanielBok/copulae

extra:
  recipe-maintainers:
    - DanielBok
