{% set name = "copulae" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a335cae03f2f8fffe1cde70e34d3fab7899f3b7c22922fbde2a2e80fa663ae2d

build:
  number: 1
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [py<36]


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.28.2
    - pip
    - numpy >=1.14
    - scipy
  run:
    - {{ pin_compatible('numpy') }}
    - pandas >=0.23
    - python
    - scipy >=1.1
    - scikit-learn >=0.23
    - statsmodels >=0.9
    - typing-extensions >=3.7.4.2  # [py<38]
    - wheel
    - wrapt

test:
  imports:
    - copulae
    - copulae.archimedean
    - copulae.copula
    - copulae.core
    - copulae.datasets
    - copulae.elliptical
    - copulae.empirical
    - copulae.gof
    - copulae.indep
    - copulae.marginal
    - copulae.mixtures
    - copulae.special
    - copulae.stats
    - copulae.utility

about:
  home: https://github.com/DanielBok/copulae
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python copulae library for dependency modelling
  description: |
    Copulae is a package for multivariate modeling
  doc_url: https://copulae.readthedocs.io/en/latest
  dev_url: https://github.com/DanielBok/copulae

extra:
  recipe-maintainers:
    - DanielBok
